# Системы линейных уравнений. Часть 1

In [1]:
import numpy as np

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Запишем расширенную матрицу системы:
#### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$
Заметим, что в данном случае число неизвестных больше числа уравнений, а это значит, что система имеет бесконечное количество решений. <br>
Вычтем из второй строки первую, умноженную на 2:
#### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$
Вычтем из третьей строки первую:
#### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$
Оставшаяся матрица указывает, что система линейных уравнений имеет бесконечное множество решений. Запишем решение в общем виде, задав переменную $x_{4}=c$ в качестве свободного параметра:
#### $$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
~~~-x_{2}+x_{3}+5x_{4}=-2, \\
~~~~~~~~~~~~-2x_{3}+3x_{4}=4.
\end{cases}$$
#### $$x_{4} = c$$
#### $$x_{3} = 1.5c-2$$
#### $$x_{2} = 6.5c$$
#### $$x_{1} = -3c-2$$
Это будет _общее решение системы_: $x=\begin{pmatrix}
-3c-2\\ 
6.5c\\ 
1.5c-2\\ 
c
\end{pmatrix}$. <br> Подставляя произвольные числа вместо $c$, будут получаться _частные решения_. Например, при $c=1$:
#### $$x_{1} = -5; x_{2} = 6.5; x_{3} = -0.5; x_{4} = 1.$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

Воспользуемся теоремой Кронекера-Капелли для решения данного задания:

а) Количество неизвестных равно количеству уравнений. Значит возможны следующие варианты: 1) система имеет одно решение; 2) система имеет бесконечное количество решений; 3) система не имеет решений.

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A_= np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
print('Количество неизвестных: 3')
print(f'Ранг матрицы коэффициентов: {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы: {np.linalg.matrix_rank(A_)}')

Количество неизвестных: 3
Ранг матрицы коэффициентов: 3
Ранг расширенной матрицы: 3


По теореме получаем, что в данном случае система _совместна_ и имеет единственное решение (_определена_).

б) Количество неизвестных равно количеству уравнений. Значит возможны следующие варианты: 1) система имеет одно решение; 2) система имеет бесконечное количество решений; 3) система не имеет решений.

In [3]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A_= np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
print('Количество неизвестных: 3')
print(f'Ранг матрицы коэффициентов: {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы: {np.linalg.matrix_rank(A_)}')

Количество неизвестных: 3
Ранг матрицы коэффициентов: 1
Ранг расширенной матрицы: 2


Разные ранги матриц указывают на то, что система _несовместна_, т.е. не имеет решений.

в) Количество неизвестных превышает количество уравнений, а это значит, что система имеет бесконечное количество решений. Подтвердим это, проверив ранги матриц:

In [4]:
A = np.array([[1, 2, 5], [3, 1, -8]])
A_= np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
print('Количество неизвестных: 3')
print(f'Ранг матрицы коэффициентов: {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы: {np.linalg.matrix_rank(A_)}')

Количество неизвестных: 3
Ранг матрицы коэффициентов: 2
Ранг расширенной матрицы: 2


Ранги матрицы коэффициентов и расширенной матрицы совпадают, но при этом меньше количества неизвестных. Значит система уравнений _совместна_ и является _неопределенной_, т.е. имеет бесконечное количество решений.

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Снова воспользуемся теоремой Кронекера-Капелли. Определим ранги матрицы коэффициентов и расширенной матрицы:

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
A_= np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
print('Количество неизвестных: 4')
print(f'Ранг матрицы коэффициентов: {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы: {np.linalg.matrix_rank(A_)}')

Количество неизвестных: 4
Ранг матрицы коэффициентов: 4
Ранг расширенной матрицы: 4


Ранги матриц равны и совпадают с количеством неизвестных, а значит система _совместна_ и _определена_.

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Преобразуем расширенную матрицу, вычтя из второй строки первую, умноженную на 4, а из третьей первую, умноженную на 7:
#### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}$$
Теперь вычтем из третьей строки вторую, умноженную на 2:
#### $$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
a-2b+c
\end{matrix}
\end{pmatrix}$$

Если $a-2b+c\neq0$, то ранг матрицы коэффициентов равен 2, а ранг расширенной матрицы $\tilde{A}$ равен 3, что по теореме Кронекера-Капелли означает, что система является _несовместной_.

# Системы линейных уравнений. Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

а) Найдем определитель матрицы коэффициентов:

#### $$detA=\begin{vmatrix}
1 & -2 \\ 
3 & -4 
\end{vmatrix}=-4+6 = 2\neq 0,$$
следовательно, система совместна. <br>
Найдем определители $detA_{1}$, $detA_{2}$:
#### $$detA_{1}=\begin{vmatrix}
1 & -2 \\ 
7 & -4
\end{vmatrix} = -4 + 14 = 10,$$
#### $$detA_{2}=\begin{vmatrix}
1 & 1 \\ 
3 & 7
\end{vmatrix} = 7 - 3 = 4.$$
Найдем решение по формулам Крамера:

#### $$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$
#### $$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2.$$

б) Найдем определитель матрицы коэффициентов:

#### $$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3 \\
2 & 4 & 1
\end{vmatrix}=2\begin{vmatrix}
1 & -3 \\
4 & 1
\end{vmatrix} + \begin{vmatrix}
1 & -3 \\
2 & 1
\end{vmatrix} + 5\begin{vmatrix}
1 & 1 \\
2 & 4
\end{vmatrix}= 2\cdot13 + 7 + 5\cdot2 = 43\neq 0,$$
следовательно, система совместна. <br>
Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:
#### $$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3 \\
1 & 4 & 1
\end{vmatrix} = 10\begin{vmatrix}
1 & -3 \\
4 & 1
\end{vmatrix} + \begin{vmatrix}
-2 & -3 \\
1 & 1
\end{vmatrix} + 5\begin{vmatrix}
-2 & 1 \\
1 & 4
\end{vmatrix} = 10\cdot13 + 1 + 5\cdot(-9) = 86,$$
#### $$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3 \\
2 & 1 & 1
\end{vmatrix} = 2\begin{vmatrix}
-2 & -3 \\
1 & 1
\end{vmatrix} - 10\begin{vmatrix}
1 & -3 \\
2 & 1
\end{vmatrix} + 5\begin{vmatrix}
1 & -2 \\
2 & 1
\end{vmatrix} = 2 - 10\cdot7+5\cdot5=-43,$$
#### $$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2 \\
2 & 4 & 1
\end{vmatrix} = 2\begin{vmatrix}
1 & -2 \\
4 & 1
\end{vmatrix} + \begin{vmatrix}
1 & -2 \\
2 & 1
\end{vmatrix} + 10\begin{vmatrix}
1 & 1 \\
2 & 4
\end{vmatrix} = 2\cdot9 + 5 +10\cdot2=43.$$
Найдем решение по формулам Крамера:

#### $$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$
#### $$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1,$$
#### $$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1.$$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

$L=(l_{ij})$ - нижняя треугольная матрица, где $l_{11}=l_{22}=...=l_{nn}=1$. Определить ее можно в процессе преобразования исходной матрицы коэффициентов к треугольному виду. <br>
a) Вычтем из второй строки первую, умноженную на $l_{21} = 2$, а из третьей первую, умноженную на $l_{31}=3$:
#### $$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$ 
Теперь вычтем из третьей строки вторую, умноженную на $l_{32} = 4$:
#### $$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$
Полученная матрица будет матрицей $U$, а искомая матрица будет выглядеть следующим образом:
#### $$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.$$
б) Вычтем из второй строки первую, умноженную на $l_{21} = 2$,из третьей первую, умноженную на $l_{31}=3$, а из четвертой первую, умноженную на $l_{41} = 4$:
#### $$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
0 & 18 & 45 & 17
\end{pmatrix}$$
Далее вычтем из третьей вторую, умноженную на $l_{32}=5$, а из четвертой вторую, умноженную на $l_{42}=6$:
#### $$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 21 & 11
\end{pmatrix}$$
Наконец из четвертой строки вычтем третью, умноженную на $l_{43}=7$:
#### $$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 4
\end{pmatrix}$$
Значит, 
#### $$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}.$$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Матрица коэффициентов $A$ будет иметь вид
#### $$A = \begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$$
Вычтем из второй строки первую, умноженную на $l_{21}=\frac{11}{2}$, а из третьей первую, умноженную на $l_{31}=\frac{9}{2}$:
#### $$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & \frac{7}{2} & -\frac{19}{2}
\end{pmatrix}$$
Теперь вычтем из третьей вторую строку, умноженную на $l_{32}=\frac{7}{3}$:
#### $$U = \begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}$$
Матрица $L$ будет выглядеть следующим образом:
#### $$L = \begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0\\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}.$$
Решим теперь систему 
#### $$Ly=b:$$
#### $$\begin{cases}
y_{1}=1, \\
\frac{11}{2}y_{1}+y_{2}=-6, \\
\frac{9}{2}y_{1}+\frac{7}{3}y_{2}+y_{3}=-5.
\end{cases}$$
Получаем следующие значения:
#### $$y_{1}=1,$$
#### $$y_{2}=-\frac{23}{2},$$
#### $$y_{3}=\frac{52}{3}.$$
Теперь необходимо решить следующую систему:
#### $$Ux=y:$$
#### $$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
\frac{3}{2}x_{2}-\frac{23}{2}x_{3}=-\frac{23}{2}, \\
\frac{52}{3}x_{3}=\frac{52}{3}.
\end{cases}$$
Получаем окончательное решение исходной системы:
#### $$x_{3}=1,$$
#### $$x_{2}=0,$$
#### $$x_{1}=-1.$$

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=-\frac{45}{9}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - (-5)^2}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15+25 \right )=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$$

Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$
Решим систему $Ly=b:$
#### $$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

Получаем следующие значения $y$:
#### $$y_{1} = 59,$$
#### $$y_{2}=-33,$$
#### $$y_{3}=-12.$$

Теперь решим систему $L^{T}x=y:$

#### $$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

Отсюда получаем итоговый ответ:
#### $$x_{3}=-4,$$
#### $$x_{2}=-5,$$
#### $$x_{1}=6.$$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [6]:
def cholesky(A, b):
    rowsA = len(A)
    columnsA = len(A[0])
    
    for i in range(1, rowsA):
        if len(A[i]) != columnsA:
            return 'Матрица A задана некорректно'
    
    if rowsA != columnsA:
        return 'Метод не может быть применен, так как матрица неквадратная'
    
    if np.linalg.det(A) == 0:
        return 'Метод не может быть применен, так как матрица коэффициентов вырождена'
    
    for i in range(1, rowsA):
        M = np.zeros(shape=(i,i))
        for j in range(i):
            M[j] = A[j][:i]
        if np.linalg.det(M) == 0:
            return 'Метод не может быть применен, так как определитель одного из главных миноров равен нулю'
        
    if not np.allclose(A, A.T):
        return 'Метод не может быть применен, так как матрица не является симметричной'
        
    w, v = np.linalg.eig(A)
    for el in w:
        if el <= 0:
            return 'Метод не может быть применен, так как матрица не является положительно определенной'
    
    L = np.zeros(shape=(rowsA, rowsA))

    for i in range(rowsA):
        sq_sum = 0
        for j in range(i+1):
            if j == i:
                L[i][j] = np.sqrt(A[i][j] - sq_sum)
            else:
                L[i][j] = 1 / L[j][j] * (A[i][j] - sum(L[i][k]*L[j][k] for k in range(j)))
                sq_sum += L[i][j]**2


    y = np.linalg.inv(L) @ b
    x = np.linalg.inv(L.T) @ y
    
    return x

In [7]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b0 = np.array([531, -460, 193])
cholesky(A, b0)

array([ 6., -5., -4.])

In [8]:
B = np.array([[2, 1, 4], [1, 1, 3], [4, 3, 14]])
b1 = np.array([16, 12, 52])
cholesky(B, b1)

array([1., 2., 3.])

In [9]:
C = np.array([[16, 4, 4, -4], [4, 10, 4, 2], [4, 4, 6, -2], [-4, 2, -2, 4]])
b2 = np.array([32, 26, 20, -6])
cholesky(C, b2)

array([ 1.,  2.,  1., -1.])