# Линейные преобразования

In [1]:
import numpy as np

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

Составим и решим характеристическое уравнение для данного оператора:
### $$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0 \Rightarrow -(1+\lambda)(6-\lambda) + 12 = 0$$
### $$(1+\lambda)(6-\lambda) = 12 \Rightarrow \lambda^2 - 5\lambda + 6=0 \Rightarrow (\lambda-2)(\lambda-3)=0.$$
Значит, собственные значения линейного оператора:
### $$\lambda_1 = 2; \lambda_2 = 3.$$
Теперь найдем собственные вектора, пользуюсь определением: _собственный вектор_ оператора $\textbf{A}$ — это такой ненулевой вектор, действие оператора на который сводится к умножению его на собственное значение:

$$\textbf{A}x=\lambda x.$$
Будем исходить из того, что собственный вектор в данном примере имеет вид $x = (x_1, x_2)$. 
1. Рассмотрим $\lambda_1 = 2$:
### $$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix} \begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix} = 2\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}.$$
Отсюда получаем систему уравнений:
### $$\left\{
\begin{array}{ll}
  -x_1 - 6x_2 = 2x_1, \\
  2x_1 + 6x_2 = 2x_2.
\end{array} \right. \Rightarrow x_1 = 2x_1 + 2x_2 \Rightarrow x_2 = -\frac{1}{2}x_1.$$
Нормируем вектор для удобства дальнейшего сравнения с результатами, полученными с помощью NumPy. Получаем следующий собственный вектор для собственного значения $\lambda_1 = 2$: $x = (\frac{1}{\sqrt{1.25}}, -\frac{1}{2\sqrt{1.25}}) = (0.8944, -0.4472)$. <br>
2. Далее рассмотрим $\lambda_2 = 3$:
### $$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix} \begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix} = 3\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}.$$
Отсюда получаем систему уравнений:
### $$\left\{
\begin{array}{ll}
  -x_1 - 6x_2 = 3x_1, \\
  2x_1 + 6x_2 = 3x_2.
\end{array} \right. \Rightarrow x_1 = 3x_1 + 3x_2 \Rightarrow x_2 = -\frac{2}{3}x_1.$$
Нормируем вектор для удобства дальнейшего сравнения с результами, полученными с помощью NumPy. В результате получаем следующий собственный вектор для собственного значения $\lambda_2 = 3$: $x = (\frac{1}{\sqrt{\frac{13}{9}}}, -\frac{2}{3\sqrt{\frac{13}{9}}}) = (0.8321, -0.5547)$. <br>

In [2]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')



print(f'v1\n{v.T[0]}')
print(f'v2\n{v.T[1]}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]
v1
[-0.89442719  0.4472136 ]
v2
[ 0.83205029 -0.5547002 ]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

Найдем собственные значения для линейного оператора:
### $$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0 \Rightarrow -(1+\lambda)^2 = 0 \Rightarrow \lambda_1=\lambda_2=-1.$$
Перейдем к нахождению собственных векторов:
### $$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix} \begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix} = -1\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}.$$
Получаем следующую систему уравнений:
### $$\left\{
\begin{array}{ll}
  -x_1 + 0x_2= -x_1, \\
  0x_1 -x_2 = -x_2.
\end{array} \right. $$
Очевидно, что этой системе удовлетворяют любые значения $x_1$ и $x_2$. В нормированном виде собственные вектора для совпадающих собственных значений могут быть заданы следующим образом: $(1, 0)$ и $(0, 1)$. Это означает, что ___любой___ вектор является собственным для линейного оператора, заданного матрицей _A_.

In [3]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')



print(f'v1\n{v.T[0]}')
print(f'v2\n{v.T[1]}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]
v1
[1. 0.]
v2
[0. 1.]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

### $$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.$$

Из этого будет следовать, что 

### $$\begin{cases}
1 + 1 =\lambda \\ 
-1 + 3 =\lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение $\lambda=2.$

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором 

### $$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}$$

Из этого будет следовать, что 

### $$\begin{cases}
-9 =3\lambda \\ 
9 =-3\lambda \\
-12=-4\lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3 \\ 
\lambda=-3 \\
\lambda=3
\end{cases}.$$

Следовательно, вектор $x=(3,-3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.