# Матрицы и матричные операции. Часть 1

In [1]:
import numpy as np
import scipy.linalg

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Для того, чтобы произведение матриц _A_ и _B_ было определено необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$. Тогда, <br>
а) произведения матриц _AB_ и _BA_ не определены; <br>
б) произведение матриц _AB_ определено, получившаяся матрица имеет размерность $2 \times 3$. Произведение _BA_ не определено; <br>
в) произведение матриц _AB_ определено, получившаяся матрица имеет размерность $8 \times 8$. Произведение _BA_ определено, получившаяся матрица имеет размерность $3 \times 3$; <br>
г) произведение матриц _AB_ определено, получившаяся матрица имеет размерность $4 \times 4$. Произведение _BA_ определено, получившаяся матрица имеет размерность $4 \times 4$.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

### $$A+B =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$$
### $$AB =\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \times \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1\cdot4 -2\cdot 0 & -1\cdot1 -2\cdot5\\ 
3\cdot4+0\cdot0 & -1\cdot3+0\cdot5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$$
### $$BA =\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \times  \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}= \begin{pmatrix}
4\cdot1 -1\cdot 3 & -4\cdot2 -1\cdot0\\ 
0\cdot1+5\cdot3 & 0\cdot(-2)+5\cdot0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
A+B

array([[ 5, -3],
       [ 3,  5]])

In [3]:
A @ B

array([[  4, -11],
       [ 12,  -3]])

In [4]:
B @ A

array([[ 1, -8],
       [15,  0]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

### $$3A-2B+4C=3\cdot\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}-2\cdot\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+4\cdot\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3\cdot1-2\cdot0+4\cdot2 & 3\cdot7-2\cdot5+4\cdot(-4)\\ 
3\cdot3-2\cdot2+4\cdot1 & 3\cdot(-6)-2\cdot(-1)+4\cdot1
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$$

In [5]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

Сначала запишем транспонированную матрицу $A^T$:
### $$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$$
Тогда, 
### $$AA^T=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}\times\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4 + 1\cdot1 & 4\cdot5 + 1\cdot(-2) & 4\cdot2 + 1\cdot3\\ 
5\cdot4 - 2\cdot1 & 5\cdot5 - 2\cdot(-2) & 5\cdot2 - 2\cdot3\\ 
2\cdot4 + 3\cdot1 & 2\cdot5 + 3\cdot(-2) & 2\cdot2 + 3\cdot3 
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13 
\end{pmatrix}$$
### $$A^TA=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}\times\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4 + 5\cdot5 + 2\cdot2 & 4\cdot1 + 5\cdot(-2) + 2\cdot3\\ 
1\cdot4 - 2\cdot5 + 3\cdot2 & 1\cdot1 - 2\cdot(-2) + 3\cdot3 
\end{pmatrix} = \begin{pmatrix}
45 & 0 \\ 
0 & 14
\end{pmatrix}$$

In [6]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [7]:
A @ A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [8]:
A.T @ A

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [9]:
def vector_product(a, b):
    if len(a) != len(b):
        return 'Произведение векторов не определено'
    else:
        result = 0
        for i in range(len(a)):
            if isinstance(a[i], (int, float)) and isinstance(b[i], (int, float)):
                result += a[i]*b[i]
            else:
                return 'Произведение векторов не может быть рассчитано, попробуйте воспользоваться другой функцией'
        return result


def matrix_product(A, B):
    rowsA = len(A)
    columnsA = len(A[0])
    rowsB = len(B)
    columnsB = len(B[0])
    
    for i in range(1, rowsA):
        if len(A[i]) != columnsA:
            return 'Матрица A задана некорректно'
        
    for i in range(1, rowsB):
        if len(B[i]) != columnsB:
            return 'Матрица B задана некорректно'
    
    if columnsA != rowsB:
        return 'Произведение матриц не определено'
    
    C = list()
    B_T = list()
    
    for j in range(columnsB):
            b_j = [B[k][j] for k in range(rowsB)]
            B_T.append(b_j)
    
    
    for i in range(rowsA):
        c_i = list()
        a_i = A[i]
        for j in range(columnsB):
            b_j = B_T[j]
            c_i.append(vector_product(a_i, b_j))
        C.append(c_i)


    return C

# Матрицы и матричные операции. Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a) $det A = sinx\cdot sinx + cosx \cdot cosx = sin^2x + cos^2x = 1;$ <br>
б) Матрица треугольная, значит $det B = 4\cdot5\cdot9 = 180;$ <br>
в) Последную строку матрицы можно представить, как разницу удвоенной второй строки и первой. Это значит, что третья строка является линейной зависимостью первых двух, а значит $det C = 0.$ Проверим рассчеты: 
### $$C =\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} $$
### $$det C = 1 \cdot \begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix} - 2 \cdot \begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix} + 3 \cdot \begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix} = 45 - 48 - 2\cdot(36-42) + 3\cdot(32-35) = -3 + 12 - 9 = 0.$$

In [10]:
x = 0.5
A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
np.linalg.det(A)

1.0

In [11]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(B)

180.0

In [12]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(C)

0.0

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

a) $det(A^2) = det(A\times A) = detA\cdot detA = 4^2 = 16;$<br>
б) Согласно свойству определителей $detA^{T}=detA$, значит $detA^T = 4;$ <br>
в) Для того, чтобы определить $det (2A)$ необходимо знать количество строк в матрице $A$. Например, если исходная матрица имеет вид $A = \begin{vmatrix}
1 & 0\\ 
0 & 4
\end{vmatrix}$, то матрица $2A = \begin{vmatrix}
2 & 0\\ 
0 & 8
\end{vmatrix}$, значит $det(2A) = 16$. Если же исходная матрица имела вид $A = \begin{vmatrix}
1 & 0 & 0\\ 
0 & 4 & 0\\
0 & 0 & 1
\end{vmatrix}$, то матрица $2A$ будет выглядеть следующим образом $2A = \begin{vmatrix}
2 & 0 & 0\\ 
0 & 8 & 0\\
0 & 0 & 2
\end{vmatrix}$ и $det(2A) = 32$. Таким образом, если матрица $A$ имеет размерность $m\times n$, то $det(2A) = 4\cdot2^m.$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Умножим первую строку на $-2$. Получаем новую матрицу $B$, для которой $det B = -2detA$:
### $$B = \begin{pmatrix}
4 & -14 & 6\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$

Видим, что первая и вторая строки одинаковые, а значит по пятому свойству определителей $det B = 0 \Rightarrow det A =0$. Значит, по определению матрица $A$ является вырожденной.

In [13]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(A)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) Третья строка является суммой первых двух, значит ранг матрица равен 2.

In [14]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(A)

2

б) Третья строка является суммой первых двух, значит ранг матрица равен 3.

In [15]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(B)

3

__5.__ Написать на Python функцию для расчета определителя матрицы по первому алгоритму.

In [16]:
def matrix_det(A):
    rowsA = len(A)
    columnsA = len(A[0])
    
    for i in range(1, rowsA):
        if len(A[i]) != columnsA:
            return 'Матрица A задана некорректно'
        
    if rowsA != columnsA:
        return 'Определитель может быть рассчитан только для квадратной матрицы'
    
    if rowsA == 1:
        return A[0]
    elif rowsA == 2:
        det = A[0][0] * A[1][1] - A[0][1]*A[1][0]
        return det
    else:
        det = 0
        for i in range(columnsA):
            B = A[1:]
            for j in range(rowsA-1):
                B[j] = B[j][:i] + B[j][i+1:]
            det += (-1)**(i+2) * matrix_det(B) * A[0][i]
        return det